#!/bin/bash

alias ls='ls --color=auto'
alias lt='ls -lrth'
alias la='ls -A'

alias reload='source ~/.bashrc'
alias lolfortune='fortune | cowsay -f moose | lolcat'

export EDITOR='vi'

# Slurm
alias squeue='squeue --format="%.18i %.50P %.8j %.8u %.2t %.10M %.6D %R"'
